[[main]]
none = "none"

[[main]]
name = "Everything"
pageRef = "everything"
identifier = "bTow8y5INW"
weight = 9

[[main]]
name = "Portfolio"
pageRef = "/tags/Portfolio"
identifier = "q2X70qb0OJ"
weight = 1

[[main]]
name = "Blog"
pageRef = "blog"
identifier = "lnwenjrnlwj"
weight = 10

[[footer]]
none = "none"
