# Site settings
title: Jonny Hopkinss
email: jwhopkins@ucdavis.edu
description: > # this means to ignore newlines until "baseurl:"
 Computer Graphics, Game Development, 3D Art + Animation
baseurl:  # the subpath of your site, e.g. /blog/
url: #the base hostname & protocol for your site
twitter_username: jwhopkin
github_username:  jwhop

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  

